Credits: this notebook belongs to [Practical DL](https://docs.google.com/forms/d/e/1FAIpQLScvrVtuwrHSlxWqHnLt1V-_7h2eON_mlRR6MUb3xEe5x9LuoA/viewform?usp=sf_link) course by Yandex School of Data Analysis.

In [34]:
%run modules.ipynb

In [35]:
import torch
import numpy
import unittest

In [36]:
class TestLayers(unittest.TestCase):
    def test_Linear(self):
        np.random.seed(42)
        torch.manual_seed(42)

        batch_size, n_in, n_out = 2, 3, 4
        for _ in range(100):
            # layers initialization
            torch_layer = torch.nn.Linear(n_in, n_out)
            custom_layer = Linear(n_in, n_out)
            custom_layer.W = torch_layer.weight.data.numpy()
            custom_layer.b = torch_layer.bias.data.numpy()

            layer_input = np.random.uniform(-10, 10, (batch_size, n_in)).astype(np.float32)
            next_layer_grad = np.random.uniform(-10, 10, (batch_size, n_out)).astype(np.float32)

            # 1. check layer output
            custom_layer_output = custom_layer.updateOutput(layer_input)
            layer_input_var = torch.from_numpy(layer_input).requires_grad_(True)
            torch_layer_output_var = torch_layer(layer_input_var)
            self.assertTrue(np.allclose(torch_layer_output_var.data.numpy(), custom_layer_output, atol=1e-6))
        
            # 2. check layer input grad
            custom_layer_grad = custom_layer.updateGradInput(layer_input, next_layer_grad)
            torch_layer_output_var.backward(torch.from_numpy(next_layer_grad))
            torch_layer_grad_var = layer_input_var.grad
            self.assertTrue(np.allclose(torch_layer_grad_var.data.numpy(), custom_layer_grad, atol=1e-6))

            # 3. check layer parameters grad
            custom_layer.accGradParameters(layer_input, next_layer_grad)
            weight_grad = custom_layer.gradW
            bias_grad = custom_layer.gradb
            torch_weight_grad = torch_layer.weight.grad.data.numpy()
            torch_bias_grad = torch_layer.bias.grad.data.numpy()
            self.assertTrue(np.allclose(torch_weight_grad, weight_grad, atol=1e-6))
            self.assertTrue(np.allclose(torch_bias_grad, bias_grad, atol=1e-6))

    def test_SoftMax(self):
        np.random.seed(42)
        torch.manual_seed(42)

        batch_size, n_in = 2, 4
        for _ in range(100):
            # layers initialization
            torch_layer = torch.nn.Softmax(dim=1)
            custom_layer = SoftMax()

            layer_input = np.random.uniform(-10, 10, (batch_size, n_in)).astype(np.float32)
            next_layer_grad = np.random.random((batch_size, n_in)).astype(np.float32)
            next_layer_grad /= next_layer_grad.sum(axis=-1, keepdims=True)
            next_layer_grad = next_layer_grad.clip(1e-5,1.)
            next_layer_grad = 1. / next_layer_grad

            # 1. check layer output
            custom_layer_output = custom_layer.updateOutput(layer_input)
            layer_input_var = torch.from_numpy(layer_input).requires_grad_(True)
            torch_layer_output_var = torch_layer(layer_input_var)
            self.assertTrue(np.allclose(torch_layer_output_var.data.numpy(), custom_layer_output, atol=1e-5))

            # 2. check layer input grad
            custom_layer_grad = custom_layer.updateGradInput(layer_input, next_layer_grad)
            torch_layer_output_var.backward(torch.from_numpy(next_layer_grad))
            torch_layer_grad_var = layer_input_var.grad
            self.assertTrue(np.allclose(torch_layer_grad_var.data.numpy(), custom_layer_grad, atol=1e-5))
            
    def test_LogSoftMax(self):
        np.random.seed(42)
        torch.manual_seed(42)

        batch_size, n_in = 2, 4
        for _ in range(100):
            # layers initialization
            torch_layer = torch.nn.LogSoftmax(dim=1)
            custom_layer = LogSoftMax()

            layer_input = np.random.uniform(-10, 10, (batch_size, n_in)).astype(np.float32)
            next_layer_grad = np.random.random((batch_size, n_in)).astype(np.float32)
            next_layer_grad /= next_layer_grad.sum(axis=-1, keepdims=True)

            # 1. check layer output
            custom_layer_output = custom_layer.updateOutput(layer_input)
            layer_input_var = torch.from_numpy(layer_input).requires_grad_(True)
            torch_layer_output_var = torch_layer(layer_input_var)
            self.assertTrue(np.allclose(torch_layer_output_var.data.numpy(), custom_layer_output, atol=1e-6))

            # 2. check layer input grad
            custom_layer_grad = custom_layer.updateGradInput(layer_input, next_layer_grad)
            torch_layer_output_var.backward(torch.from_numpy(next_layer_grad))
            torch_layer_grad_var = layer_input_var.grad
            self.assertTrue(np.allclose(torch_layer_grad_var.data.numpy(), custom_layer_grad, atol=1e-6))

    def test_BatchNormalization(self):
        np.random.seed(42)
        torch.manual_seed(42)

        batch_size, n_in = 32, 16
        for _ in range(100):
            # layers initialization
            slope = np.random.uniform(0.01, 0.05)
            alpha = 0.9
            custom_layer = BatchNormalization(alpha)
            custom_layer.train()
            torch_layer = torch.nn.BatchNorm1d(n_in, eps=custom_layer.EPS, momentum=1.-alpha, affine=False)
            custom_layer.moving_mean = torch_layer.running_mean.numpy().copy()
            custom_layer.moving_variance = torch_layer.running_var.numpy().copy()

            layer_input = np.random.uniform(-5, 5, (batch_size, n_in)).astype(np.float32)
            next_layer_grad = np.random.uniform(-5, 5, (batch_size, n_in)).astype(np.float32)

            # 1. check layer output
            custom_layer_output = custom_layer.updateOutput(layer_input)
            layer_input_var = torch.from_numpy(layer_input).requires_grad_(True)
            torch_layer_output_var = torch_layer(layer_input_var)
            self.assertTrue(np.allclose(torch_layer_output_var.data.numpy(), custom_layer_output, atol=1e-6))

            # 2. check layer input grad
            custom_layer_grad = custom_layer.updateGradInput(layer_input, next_layer_grad)
            torch_layer_output_var.backward(torch.from_numpy(next_layer_grad))
            torch_layer_grad_var = layer_input_var.grad
            # please, don't increase `atol` parameter, it's garanteed that you can implement batch norm layer
            # with tolerance 1e-5
            self.assertTrue(np.allclose(torch_layer_grad_var.data.numpy(), custom_layer_grad, atol=1e-5))

            # 3. check moving mean
            self.assertTrue(np.allclose(custom_layer.moving_mean, torch_layer.running_mean.numpy()))
            # we don't check moving_variance because pytorch uses slightly different formula for it:
            # it computes moving average for unbiased variance (i.e var*N/(N-1))
            #self.assertTrue(np.allclose(custom_layer.moving_variance, torch_layer.running_var.numpy()))

            # 4. check evaluation mode
            custom_layer.moving_variance = torch_layer.running_var.numpy().copy()
            custom_layer.evaluate()
            custom_layer_output = custom_layer.updateOutput(layer_input)
            torch_layer.eval()
            torch_layer_output_var = torch_layer(layer_input_var)
            self.assertTrue(np.allclose(torch_layer_output_var.data.numpy(), custom_layer_output, atol=1e-6))
            
    def test_Sequential(self):
        np.random.seed(42)
        torch.manual_seed(42)

        batch_size, n_in = 2, 4
        for _ in range(100):
            # layers initialization
            alpha = 0.9
            torch_layer = torch.nn.BatchNorm1d(n_in, eps=BatchNormalization.EPS, momentum=1.-alpha, affine=True)
            torch_layer.bias.data = torch.from_numpy(np.random.random(n_in).astype(np.float32))
            custom_layer = Sequential()
            bn_layer = BatchNormalization(alpha)
            bn_layer.moving_mean = torch_layer.running_mean.numpy().copy()
            bn_layer.moving_variance = torch_layer.running_var.numpy().copy()
            custom_layer.add(bn_layer)
            scaling_layer = ChannelwiseScaling(n_in)
            scaling_layer.gamma = torch_layer.weight.data.numpy()
            scaling_layer.beta = torch_layer.bias.data.numpy()
            custom_layer.add(scaling_layer)
            custom_layer.train()

            layer_input = np.random.uniform(-5, 5, (batch_size, n_in)).astype(np.float32)
            next_layer_grad = np.random.uniform(-5, 5, (batch_size, n_in)).astype(np.float32)

            # 1. check layer output
            custom_layer_output = custom_layer.updateOutput(layer_input)
            layer_input_var = torch.from_numpy(layer_input).requires_grad_(True)
            torch_layer_output_var = torch_layer(layer_input_var)
            self.assertTrue(np.allclose(torch_layer_output_var.data.numpy(), custom_layer_output, atol=1e-6))

            # 2. check layer input grad
            custom_layer_grad = custom_layer.backward(layer_input, next_layer_grad)
            torch_layer_output_var.backward(torch.from_numpy(next_layer_grad))
            torch_layer_grad_var = layer_input_var.grad
            self.assertTrue(np.allclose(torch_layer_grad_var.data.numpy(), custom_layer_grad, atol=1e-5))

            # 3. check layer parameters grad
            weight_grad, bias_grad = custom_layer.getGradParameters()[1]
            torch_weight_grad = torch_layer.weight.grad.data.numpy()
            torch_bias_grad = torch_layer.bias.grad.data.numpy()
#             print(np.max(torch_weight_grad - weight_grad))
#             print(weight_grad)
#             print(torch_weight_grad)
#             print(bias_grad)
#             print(torch_bias_grad)
#             print(f'{torch_layer.weight=}')
#             print(f'{torch_layer.bias=}')
#             print(f'{custom_layer.getParameters()[1]=}')
#             print(torch_layer.running_mean)
#             print(bn_layer.moving_mean)
#             print(torch_layer.running_var)
#             print(bn_layer.moving_variance)
            self.assertTrue(np.allclose(torch_weight_grad, weight_grad, atol=1e-6))
            self.assertTrue(np.allclose(torch_bias_grad, bias_grad, atol=1e-6))

    def test_Dropout(self):
        np.random.seed(42)

        batch_size, n_in = 2, 4
        for _ in range(100):
            # layers initialization
            p = np.random.uniform(0.3, 0.7)
            layer = Dropout(p)
            layer.train()

            layer_input = np.random.uniform(-5, 5, (batch_size, n_in)).astype(np.float32)
            next_layer_grad = np.random.uniform(-5, 5, (batch_size, n_in)).astype(np.float32)

            # 1. check layer output
            layer_output = layer.updateOutput(layer_input)
            self.assertTrue(np.all(np.logical_or(np.isclose(layer_output, 0), 
                                        np.isclose(layer_output*(1.-p), layer_input))))

            # 2. check layer input grad
            layer_grad = layer.updateGradInput(layer_input, next_layer_grad)
            self.assertTrue(np.all(np.logical_or(np.isclose(layer_grad, 0), 
                                        np.isclose(layer_grad*(1.-p), next_layer_grad))))

            # 3. check evaluation mode
            layer.evaluate()
            layer_output = layer.updateOutput(layer_input)
            self.assertTrue(np.allclose(layer_output, layer_input))

            # 4. check mask
            p = 0.0
            layer = Dropout(p)
            layer.train()
            layer_output = layer.updateOutput(layer_input)
            self.assertTrue(np.allclose(layer_output, layer_input))

            p = 0.5
            layer = Dropout(p)
            layer.train()
            layer_input = np.random.uniform(5, 10, (batch_size, n_in)).astype(np.float32)
            next_layer_grad = np.random.uniform(5, 10, (batch_size, n_in)).astype(np.float32)
            layer_output = layer.updateOutput(layer_input)
            zeroed_elem_mask = np.isclose(layer_output, 0)
            layer_grad = layer.updateGradInput(layer_input, next_layer_grad)        
            self.assertTrue(np.all(zeroed_elem_mask == np.isclose(layer_grad, 0)))

            # 5. dropout mask should be generated independently for every input matrix element, not for row/column
            batch_size, n_in = 1000, 1
            p = 0.8
            layer = Dropout(p)
            layer.train()

            layer_input = np.random.uniform(5, 10, (batch_size, n_in)).astype(np.float32)
            layer_output = layer.updateOutput(layer_input)
            self.assertTrue(np.sum(np.isclose(layer_output, 0)) != layer_input.size)

            layer_input = layer_input.T
            layer_output = layer.updateOutput(layer_input)
            self.assertTrue(np.sum(np.isclose(layer_output, 0)) != layer_input.size)
    def test_LeakyReLU(self):
        np.random.seed(42)
        torch.manual_seed(42)

        batch_size, n_in = 2, 4
        for _ in range(100):
            # layers initialization
            slope = np.random.uniform(0.01, 0.05)
            torch_layer = torch.nn.LeakyReLU(slope)
            custom_layer = LeakyReLU(slope)

            layer_input = np.random.uniform(-5, 5, (batch_size, n_in)).astype(np.float32)
            next_layer_grad = np.random.uniform(-5, 5, (batch_size, n_in)).astype(np.float32)

            # 1. check layer output
            custom_layer_output = custom_layer.updateOutput(layer_input)
            layer_input_var = torch.from_numpy(layer_input).requires_grad_(True)
            torch_layer_output_var = torch_layer(layer_input_var)
            self.assertTrue(np.allclose(torch_layer_output_var.data.numpy(), custom_layer_output, atol=1e-6))

            # 2. check layer input grad
            custom_layer_grad = custom_layer.updateGradInput(layer_input, next_layer_grad)
            torch_layer_output_var.backward(torch.from_numpy(next_layer_grad))
            torch_layer_grad_var = layer_input_var.grad
            self.assertTrue(np.allclose(torch_layer_grad_var.data.numpy(), custom_layer_grad, atol=1e-6))

    def test_ELU(self):
        np.random.seed(42)
        torch.manual_seed(42)

        batch_size, n_in = 2, 4
        for _ in range(100):
            # layers initialization
            alpha = 1.0
            torch_layer = torch.nn.ELU(alpha)
            custom_layer = ELU(alpha)

            layer_input = np.random.uniform(-5, 5, (batch_size, n_in)).astype(np.float32)
            next_layer_grad = np.random.uniform(-5, 5, (batch_size, n_in)).astype(np.float32)

            # 1. check layer output
            custom_layer_output = custom_layer.updateOutput(layer_input)
            layer_input_var = torch.from_numpy(layer_input).requires_grad_(True)
            torch_layer_output_var = torch_layer(layer_input_var)
            self.assertTrue(np.allclose(torch_layer_output_var.data.numpy(), custom_layer_output, atol=1e-6))

            # 2. check layer input grad
            custom_layer_grad = custom_layer.updateGradInput(layer_input, next_layer_grad)
            torch_layer_output_var.backward(torch.from_numpy(next_layer_grad))
            torch_layer_grad_var = layer_input_var.grad
            self.assertTrue(np.allclose(torch_layer_grad_var.data.numpy(), custom_layer_grad, atol=1e-6))

    def test_SoftPlus(self):
        np.random.seed(42)
        torch.manual_seed(42)

        batch_size, n_in = 2, 4
        for _ in range(100):
            # layers initialization
            torch_layer = torch.nn.Softplus()
            custom_layer = SoftPlus()

            layer_input = np.random.uniform(-5, 5, (batch_size, n_in)).astype(np.float32)
            next_layer_grad = np.random.uniform(-5, 5, (batch_size, n_in)).astype(np.float32)

            # 1. check layer output
            custom_layer_output = custom_layer.updateOutput(layer_input)
            layer_input_var = torch.from_numpy(layer_input).requires_grad_(True)
            torch_layer_output_var = torch_layer(layer_input_var)
            self.assertTrue(np.allclose(torch_layer_output_var.data.numpy(), custom_layer_output, atol=1e-6))

            # 2. check layer input grad
            custom_layer_grad = custom_layer.updateGradInput(layer_input, next_layer_grad)
            torch_layer_output_var.backward(torch.from_numpy(next_layer_grad))
            torch_layer_grad_var = layer_input_var.grad
            self.assertTrue(np.allclose(torch_layer_grad_var.data.numpy(), custom_layer_grad, atol=1e-6))

    def test_ClassNLLCriterionUnstable(self):
        np.random.seed(42)
        torch.manual_seed(42)

        batch_size, n_in = 2, 4
        for _ in range(100):
            # layers initialization
            torch_layer = torch.nn.NLLLoss()
            custom_layer = ClassNLLCriterionUnstable()

            layer_input = np.random.uniform(0, 1, (batch_size, n_in)).astype(np.float32)
            layer_input /= layer_input.sum(axis=-1, keepdims=True)
            layer_input = layer_input.clip(custom_layer.EPS, 1. - custom_layer.EPS)  # unifies input
            target_labels = np.random.choice(n_in, batch_size)
            target = np.zeros((batch_size, n_in), np.float32)
            target[np.arange(batch_size), target_labels] = 1  # one-hot encoding

            # 1. check layer output
            custom_layer_output = custom_layer.updateOutput(layer_input, target)
            layer_input_var = torch.from_numpy(layer_input).requires_grad_(True)
            torch_layer_output_var = torch_layer(
                torch.log(layer_input_var),
                torch.from_numpy(target_labels))
            self.assertTrue(np.allclose(torch_layer_output_var.data.numpy(), custom_layer_output, atol=1e-6))

            # 2. check layer input grad
            custom_layer_grad = custom_layer.updateGradInput(layer_input, target)
            torch_layer_output_var.backward()
            torch_layer_grad_var = layer_input_var.grad
            self.assertTrue(np.allclose(torch_layer_grad_var.data.numpy(), custom_layer_grad, atol=1e-6))

    def test_ClassNLLCriterion(self):
        np.random.seed(42)
        torch.manual_seed(42)

        batch_size, n_in = 2, 4
        for _ in range(100):
            # layers initialization
            torch_layer = torch.nn.NLLLoss()
            custom_layer = ClassNLLCriterion()

            layer_input = np.random.uniform(-5, 5, (batch_size, n_in)).astype(np.float32)
            layer_input = torch.nn.LogSoftmax(dim=1)(torch.from_numpy(layer_input)).data.numpy()
            target_labels = np.random.choice(n_in, batch_size)
            target = np.zeros((batch_size, n_in), np.float32)
            target[np.arange(batch_size), target_labels] = 1  # one-hot encoding

            # 1. check layer output
            custom_layer_output = custom_layer.updateOutput(layer_input, target)
            layer_input_var = torch.from_numpy(layer_input).requires_grad_(True)
            torch_layer_output_var = torch_layer(
                layer_input_var,
                torch.from_numpy(target_labels)
            )
            self.assertTrue(np.allclose(torch_layer_output_var.data.numpy(), custom_layer_output, atol=1e-6))

            # 2. check layer input grad
            custom_layer_grad = custom_layer.updateGradInput(layer_input, target)
            torch_layer_output_var.backward()
            torch_layer_grad_var = layer_input_var.grad
            self.assertTrue(np.allclose(torch_layer_grad_var.data.numpy(), custom_layer_grad, atol=1e-6))
            
    def test_adam_optimizer(self):
        state = {}  
        config = {'learning_rate': 1e-3, 'beta1': 0.9, 'beta2':0.999, 'epsilon':1e-8}
        variables = [[np.arange(10).astype(np.float64)]]
        gradients = [[np.arange(10).astype(np.float64)]]
        adam_optimizer(variables, gradients, config, state)
        self.assertTrue(np.allclose(state['m'][0], np.array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 
                                                             0.6, 0.7, 0.8, 0.9])))
        self.assertTrue(np.allclose(state['v'][0], np.array([0., 0.001, 0.004, 0.009, 0.016, 0.025, 
                                                             0.036, 0.049, 0.064, 0.081])))
        self.assertTrue(state['t'] == 1)
        self.assertTrue(np.allclose(variables[0][0], np.array([0., 0.999, 1.999, 2.999, 3.999, 4.999, 
                                                               5.999, 6.999, 7.999, 8.999])))
        adam_optimizer(variables, gradients, config, state)
        self.assertTrue(np.allclose(state['m'][0], np.array([0., 0.19, 0.38, 0.57, 0.76, 0.95, 1.14, 
                                                             1.33, 1.52, 1.71])))
        self.assertTrue(np.allclose(state['v'][0], np.array([0., 0.001999, 0.007996, 0.017991, 
                                                             0.031984, 0.049975, 0.071964, 0.097951, 
                                                             0.127936, 0.161919])))
        self.assertTrue(state['t'] == 2)
        self.assertTrue(np.allclose(variables[0][0], np.array([0., 0.998, 1.998, 2.998, 3.998, 4.998, 
                                                               5.998, 6.998, 7.998, 8.998])))
    
suite = unittest.TestLoader().loadTestsFromTestCase(TestLayers)
unittest.TextTestRunner(verbosity=2).run(suite)

test_BatchNormalization (__main__.TestLayers) ... ok
test_ClassNLLCriterion (__main__.TestLayers) ... ok
test_ClassNLLCriterionUnstable (__main__.TestLayers) ... ok
test_Dropout (__main__.TestLayers) ... ok
test_ELU (__main__.TestLayers) ... ok
test_LeakyReLU (__main__.TestLayers) ... ok
test_Linear (__main__.TestLayers) ... ok
test_LogSoftMax (__main__.TestLayers) ... ok
test_Sequential (__main__.TestLayers) ... FAIL
test_SoftMax (__main__.TestLayers) ... ok
test_SoftPlus (__main__.TestLayers) ... ok
test_adam_optimizer (__main__.TestLayers) ... ok

FAIL: test_Sequential (__main__.TestLayers)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/folders/r_/bq4swdms3vj5wr80yf1vm4nh0000gn/T/ipykernel_39376/1518887316.py", line 166, in test_Sequential
    self.assertTrue(np.allclose(torch_layer_output_var.data.numpy(), custom_layer_output, atol=1e-6))
AssertionError: False is not true

--------------------------------------

<unittest.runner.TextTestResult run=12 errors=0 failures=1>

In [37]:
class TestAdvancedLayers(unittest.TestCase):
    def test_Conv2d(self):
        np.random.seed(42)
        torch.manual_seed(42)

        batch_size, n_in, n_out = 2, 3, 4
        h,w = 5,6
        kern_size = 3
        for _ in range(100):
            # layers initialization
            torch_layer = torch.nn.Conv2d(n_in, n_out, kern_size, padding=1)
            custom_layer = Conv2d(n_in, n_out, kern_size)
            custom_layer.W = torch_layer.weight.data.numpy() # [n_out, n_in, kern, kern]
            custom_layer.b = torch_layer.bias.data.numpy()

            layer_input = np.random.uniform(-1, 1, (batch_size, n_in, h,w)).astype(np.float32)
            next_layer_grad = np.random.uniform(-1, 1, (batch_size, n_out, h, w)).astype(np.float32)

            # 1. check layer output
            custom_layer_output = custom_layer.updateOutput(layer_input)
            layer_input_var = torch.from_numpy(layer_input).requires_grad_(True)
            torch_layer_output_var = torch_layer(layer_input_var)
            self.assertTrue(np.allclose(torch_layer_output_var.data.numpy(), custom_layer_output, atol=1e-6))
        
            # 2. check layer input grad
            custom_layer_grad = custom_layer.updateGradInput(layer_input, next_layer_grad)
            torch_layer_output_var.backward(torch.from_numpy(next_layer_grad))
            torch_layer_grad_var = layer_input_var.grad
            self.assertTrue(np.allclose(torch_layer_grad_var.data.numpy(), custom_layer_grad, atol=1e-6))
            
            # 3. check layer parameters grad
            custom_layer.accGradParameters(layer_input, next_layer_grad)
            weight_grad = custom_layer.gradW
            bias_grad = custom_layer.gradb
            torch_weight_grad = torch_layer.weight.grad.data.numpy()
            torch_bias_grad = torch_layer.bias.grad.data.numpy()
            #m = ~np.isclose(torch_weight_grad, weight_grad, atol=1e-5)
            self.assertTrue(np.allclose(torch_weight_grad, weight_grad, atol=1e-6, ))
            self.assertTrue(np.allclose(torch_bias_grad, bias_grad, atol=1e-6))
            
    def test_MaxPool2d(self):
        np.random.seed(42)
        torch.manual_seed(42)

        batch_size, n_in = 2, 3
        h,w = 4,6
        kern_size = 2
        for _ in range(100):
            # layers initialization
            torch_layer = torch.nn.MaxPool2d(kern_size)
            custom_layer = MaxPool2d(kern_size)

            layer_input = np.random.uniform(-10, 10, (batch_size, n_in, h,w)).astype(np.float32)
            next_layer_grad = np.random.uniform(-10, 10, (batch_size, n_in, 
                                                          h // kern_size, w // kern_size)).astype(np.float32)

            # 1. check layer output
            custom_layer_output = custom_layer.updateOutput(layer_input)
            layer_input_var = torch.from_numpy(layer_input).requires_grad_(True)
            torch_layer_output_var = torch_layer(layer_input_var)
            self.assertTrue(np.allclose(torch_layer_output_var.data.numpy(), custom_layer_output, atol=1e-6))
        
            # 2. check layer input grad
            custom_layer_grad = custom_layer.updateGradInput(layer_input, next_layer_grad)
            torch_layer_output_var.backward(torch.from_numpy(next_layer_grad))
            torch_layer_grad_var = layer_input_var.grad
            self.assertTrue(np.allclose(torch_layer_grad_var.data.numpy(), custom_layer_grad, atol=1e-6))


suite = unittest.TestLoader().loadTestsFromTestCase(TestAdvancedLayers)
unittest.TextTestRunner(verbosity=2).run(suite)

test_Conv2d (__main__.TestAdvancedLayers) ... 

[[-0.16843465 -0.16843465 -0.16843465 -0.16843465 -0.16843465 -0.16843465]
 [-0.16843465 -0.16843465 -0.16843465 -0.16843465 -0.16843465 -0.16843465]
 [-0.16843465 -0.16843465 -0.16843465 -0.16843465 -0.16843465 -0.16843465]
 [-0.16843465 -0.16843465 -0.16843465 -0.16843465 -0.16843465 -0.16843465]
 [-0.16843465 -0.16843465 -0.16843465 -0.16843465 -0.16843465 -0.16843465]]
----------------------------------------------------------------------------------------------------
[[-0.16843465 -0.16843465 -0.16843465 -0.16843465 -0.16843465 -0.16843465]
 [-0.16843465 -0.16843465 -0.16843465 -0.16843465 -0.16843465 -0.16843465]
 [-0.16843465 -0.16843465 -0.16843465 -0.16843465 -0.16843465 -0.16843465]
 [-0.16843465 -0.16843465 -0.16843465 -0.16843465 -0.16843465 -0.16843465]
 [-0.16843465 -0.16843465 -0.16843465 -0.16843465 -0.16843465 -0.16843465]]
####################################################################################################
----------------------------------------------

[[-0.18098202 -0.18098202 -0.18098202 -0.18098202 -0.18098202 -0.18098202]
 [-0.18098202 -0.18098202 -0.18098202 -0.18098202 -0.18098202 -0.18098202]
 [-0.18098202 -0.18098202 -0.18098202 -0.18098202 -0.18098202 -0.18098202]
 [-0.18098202 -0.18098202 -0.18098202 -0.18098202 -0.18098202 -0.18098202]
 [-0.18098202 -0.18098202 -0.18098202 -0.18098202 -0.18098202 -0.18098202]]
----------------------------------------------------------------------------------------------------
[[-0.18098202 -0.18098202 -0.18098202 -0.18098202 -0.18098202 -0.18098202]
 [-0.18098202 -0.18098202 -0.18098202 -0.18098202 -0.18098202 -0.18098202]
 [-0.18098202 -0.18098202 -0.18098202 -0.18098202 -0.18098202 -0.18098202]
 [-0.18098202 -0.18098202 -0.18098202 -0.18098202 -0.18098202 -0.18098202]
 [-0.18098202 -0.18098202 -0.18098202 -0.18098202 -0.18098202 -0.18098202]]
####################################################################################################
----------------------------------------------

 [-0.14458853 -0.14458853 -0.14458853 -0.14458853 -0.14458853 -0.14458853]]
----------------------------------------------------------------------------------------------------
[[-0.14458853 -0.14458853 -0.14458853 -0.14458853 -0.14458853 -0.14458853]
 [-0.14458853 -0.14458853 -0.14458853 -0.14458853 -0.14458853 -0.14458853]
 [-0.14458853 -0.14458853 -0.14458853 -0.14458853 -0.14458853 -0.14458853]
 [-0.14458853 -0.14458853 -0.14458853 -0.14458853 -0.14458853 -0.14458853]
 [-0.14458853 -0.14458853 -0.14458853 -0.14458853 -0.14458853 -0.14458853]]
####################################################################################################
----------------------------------------------------------------------------------------------------
[[ 0.15987152 -0.18708254  0.17937827  0.01584259  0.09772047 -0.13680547]
 [-0.30012432 -0.00745985 -0.02304913 -0.03891014 -0.26747303 -0.21668556]
 [-0.32306531 -0.26741899 -0.38967916 -0.13813803 -0.06138098 -0.13145803]
 [-0.20447928  0.064

 [ 0.07076428  0.0889299   0.05870632  0.05704095  0.08726622  0.12399418]]
####################################################################################################
----------------------------------------------------------------------------------------------------
[[-0.14624618  0.1982149   0.11028384  0.17427832 -0.19632903 -0.183906  ]
 [ 0.11361585 -0.19678169  0.2098524   0.07766294 -0.21766937 -0.04289328]
 [ 0.12846505 -0.12272329 -0.07450491  0.09050107  0.23574442 -0.04050889]
 [-0.16331135  0.29532454  0.00489718 -0.12696529  0.5659796   0.05465929]
 [ 0.08377014  0.0689922   0.14200553 -0.06065737  0.24709327  0.17101052]]
####################################################################################################
[[-0.00929686 -0.00929686 -0.00929686 -0.00929686 -0.00929686 -0.00929686]
 [-0.00929686 -0.00929686 -0.00929686 -0.00929686 -0.00929686 -0.00929686]
 [-0.00929686 -0.00929686 -0.00929686 -0.00929686 -0.00929686 -0.00929686]
 [-0.00929686 -0.009

 [-0.16881696  0.16043883  0.12629957  0.12127953  0.12861477 -0.20933367]]
####################################################################################################
[[-0.06764404 -0.06764404 -0.06764404 -0.06764404 -0.06764404 -0.06764404]
 [-0.06764404 -0.06764404 -0.06764404 -0.06764404 -0.06764404 -0.06764404]
 [-0.06764404 -0.06764404 -0.06764404 -0.06764404 -0.06764404 -0.06764404]
 [-0.06764404 -0.06764404 -0.06764404 -0.06764404 -0.06764404 -0.06764404]
 [-0.06764404 -0.06764404 -0.06764404 -0.06764404 -0.06764404 -0.06764404]]
----------------------------------------------------------------------------------------------------
[[-0.06764404 -0.06764404 -0.06764404 -0.06764404 -0.06764404 -0.06764404]
 [-0.06764404 -0.06764404 -0.06764404 -0.06764404 -0.06764404 -0.06764404]
 [-0.06764404 -0.06764404 -0.06764404 -0.06764404 -0.06764404 -0.06764404]
 [-0.06764404 -0.06764404 -0.06764404 -0.06764404 -0.06764404 -0.06764404]
 [-0.06764404 -0.06764404 -0.06764404 -0.06764

 [-0.03897934 -0.03897934 -0.03897934 -0.03897934 -0.03897934 -0.03897934]]
####################################################################################################
----------------------------------------------------------------------------------------------------
[[ 0.0598367   0.17664768  0.0223261  -0.11323436  0.06005319  0.22469144]
 [ 0.21004777 -0.02439059 -0.09531174 -0.00514007  0.25904553  0.138606  ]
 [-0.18138558 -0.21608236 -0.12552591  0.13957518  0.25290392 -0.22067834]
 [-0.09913544  0.12654045  0.08203117  0.37579466 -0.04177127 -0.15274519]
 [-0.03411182 -0.19850245 -0.10000237 -0.03305002 -0.29331391 -0.18635848]]
####################################################################################################
----------------------------------------------------------------------------------------------------
[[-0.05581401  0.01930687 -0.07302619 -0.19582523 -0.10069361  0.25127305]
 [ 0.2206943  -0.00836951 -0.11319139 -0.01029673  0.16495109  0.0287

 [-0.04709549 -0.04709549 -0.04709549 -0.04709549 -0.04709549 -0.04709549]]
----------------------------------------------------------------------------------------------------
[[-0.04709549 -0.04709549 -0.04709549 -0.04709549 -0.04709549 -0.04709549]
 [-0.04709549 -0.04709549 -0.04709549 -0.04709549 -0.04709549 -0.04709549]
 [-0.04709549 -0.04709549 -0.04709549 -0.04709549 -0.04709549 -0.04709549]
 [-0.04709549 -0.04709549 -0.04709549 -0.04709549 -0.04709549 -0.04709549]
 [-0.04709549 -0.04709549 -0.04709549 -0.04709549 -0.04709549 -0.04709549]]
####################################################################################################
----------------------------------------------------------------------------------------------------
[[-0.16669314  0.31084462 -0.05572102 -0.16071244  0.16162972  0.07090981]
 [-0.15666702  0.14623265 -0.05561796 -0.11548752  0.01139525  0.12657411]
 [-0.18956612 -0.07729442 -0.01647315  0.23507585 -0.29186305 -0.01612862]
 [-0.28687975 -0.226

[[0.10216747 0.10216747 0.10216747 0.10216747 0.10216747 0.10216747]
 [0.10216747 0.10216747 0.10216747 0.10216747 0.10216747 0.10216747]
 [0.10216747 0.10216747 0.10216747 0.10216747 0.10216747 0.10216747]
 [0.10216747 0.10216747 0.10216747 0.10216747 0.10216747 0.10216747]
 [0.10216747 0.10216747 0.10216747 0.10216747 0.10216747 0.10216747]]
----------------------------------------------------------------------------------------------------
[[0.10216747 0.10216747 0.10216747 0.10216747 0.10216747 0.10216747]
 [0.10216747 0.10216747 0.10216747 0.10216747 0.10216747 0.10216747]
 [0.10216747 0.10216747 0.10216747 0.10216747 0.10216747 0.10216747]
 [0.10216747 0.10216747 0.10216747 0.10216747 0.10216747 0.10216747]
 [0.10216747 0.10216747 0.10216747 0.10216747 0.10216747 0.10216747]]
####################################################################################################
----------------------------------------------------------------------------------------------------
[[-0.

ok
test_MaxPool2d (__main__.TestAdvancedLayers) ... 

####################################################################################################
----------------------------------------------------------------------------------------------------
[[ 0.15903233  0.2476533   0.11269014  0.22217855 -0.011116    0.13139372]
 [ 0.16841857 -0.01014917  0.22826179  0.31746465  0.08228465  0.32443045]
 [ 0.37179396 -0.11544414  0.36595038  0.24685091 -0.0097162   0.18887025]
 [ 0.2944065   0.06670265  0.09315878  0.25292478  0.36559524 -0.20226155]
 [ 0.04710058  0.53416707 -0.21843989  0.1691974   0.49542989  0.00526799]]
####################################################################################################
----------------------------------------------------------------------------------------------------
[[ 0.09690281  0.16858251  0.18424928  0.11633967  0.22628415  0.06273209]
 [ 0.0750645   0.04292477  0.31584008  0.42472167 -0.1084593   0.34062468]
 [ 0.36463258 -0.13258542  0.19165836  0.38672455  0.07924014  0.11745

ok

----------------------------------------------------------------------
Ran 2 tests in 3.180s

OK


<unittest.runner.TextTestResult run=2 errors=0 failures=0>